version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ragdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  qdrant:
    image: qdrant/qdrant:v1.9.1
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  web:
    build: .
    container_name: rag_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - postgres_url=postgresql://postgres:postgres@postgres:5432/ragdb
      - qdrant_host=qdrant
      - qdrant_port=6333
      - redis_url=redis://redis:6379/0
      - ollama_host=http://ollama:11434
    depends_on:
      - postgres
      - redis
      - qdrant
      - ollama

volumes:
  postgres_data:
  redis_data:
  qdrant_data:
  ollama_data:
